### ISSUE TITLE
Draft 23

### ISSUE THREAD

**Issue by juliens** [juliens/quic-go#1]
# Transport
 - [ ] Rules for preventing correlation by connection ID tightened
      (https://github.com/quicwg/base-drafts/issues/2084, https://github.com/quicwg/base-drafts/issues/2929)

 - [ ] Clarified use of CONNECTION_CLOSE in Handshake packets (https://github.com/quicwg/base-drafts/issues/2151,
      https://github.com/quicwg/base-drafts/issues/2541, https://github.com/quicwg/base-drafts/issues/2688)

 - [ ] Discourage regressions of largest acknowledged in ACK (https://github.com/quicwg/base-drafts/issues/2205,
      https://github.com/quicwg/base-drafts/issues/2752)

 - [ ] Improved robusness of validation process for ECN counts (https://github.com/quicwg/base-drafts/issues/2534,
      https://github.com/quicwg/base-drafts/issues/2752)

 - [ ] Require endpoints to ignore spurious migration attempts (https://github.com/quicwg/base-drafts/issues/2342,
      https://github.com/quicwg/base-drafts/issues/2893)

 - [ ] Transport parameter for disabling migration clarified to allow NAT
      rebinding (https://github.com/quicwg/base-drafts/issues/2389, https://github.com/quicwg/base-drafts/issues/2893)

 - [ ] Document principles for defining new error codes (https://github.com/quicwg/base-drafts/issues/2388, https://github.com/quicwg/base-drafts/issues/2880)

 - [ ] Reserve transport parameters for greasing (https://github.com/quicwg/base-drafts/issues/2550, https://github.com/quicwg/base-drafts/issues/2873)

 - [ ] A maximum ACK delay of 0 is used for handshake packet number
      spaces (https://github.com/quicwg/base-drafts/issues/2646, https://github.com/quicwg/base-drafts/issues/2638)

 - [ ] Improved rules for use of congestion control state on new paths
      (https://github.com/quicwg/base-drafts/issues/2685, https://github.com/quicwg/base-drafts/issues/2918)

 - [ ] Removed recommendation to coordinate spin for multiple connections
      that share a path (https://github.com/quicwg/base-drafts/issues/2763, https://github.com/quicwg/base-drafts/issues/2882)

 - [ ] Allow smaller stateless resets and recommend a smaller minimum on
      packets that might trigger a stateless reset (https://github.com/quicwg/base-drafts/issues/2770, https://github.com/quicwg/base-drafts/issues/2869, https://github.com/quicwg/base-drafts/issues/2927)

 - [ ] Provide guidance around the interface to QUIC as used by
      application protocols (https://github.com/quicwg/base-drafts/issues/2805, https://github.com/quicwg/base-drafts/issues/2857)

 - [ ] Frames other than STREAM can cause STREAM_LIMIT_ERROR (https://github.com/quicwg/base-drafts/issues/2825,
      https://github.com/quicwg/base-drafts/issues/2826)

# recovery
 - [ ] PTO should always send an ack-eliciting packet (https://github.com/quicwg/base-drafts/issues/2895)

 - [ ] Unify the Handshake Timer with the PTO timer (https://github.com/quicwg/base-drafts/issues/2648, https://github.com/quicwg/base-drafts/issues/2658, https://github.com/quicwg/base-drafts/issues/2886)

 - [ ] Move ACK generation text to transport draft (https://github.com/quicwg/base-drafts/issues/1860, https://github.com/quicwg/base-drafts/issues/2916)

# TLS
 - [ ] Update the salt used for Initial secrets (https://github.com/quicwg/base-drafts/issues/2887, https://github.com/quicwg/base-drafts/issues/2980)

# HTTP
 - [ ] Removed priority signaling (https://github.com/quicwg/base-drafts/issues/2922,https://github.com/quicwg/base-drafts/issues/2924)

 - [x] Further changes to error codes (https://github.com/quicwg/base-drafts/issues/2662,https://github.com/quicwg/base-drafts/issues/2551):
     Fix by https://github.com/lucas-clemente/quic-go/pull/2112
      *  Error codes renumbered

      *  HTTP_MALFORMED_FRAME replaced by HTTP_FRAME_ERROR,
         HTTP_ID_ERROR, and others

 - [ ] Clarify how unknown frame types interact with required frame
      sequence (https://github.com/quicwg/base-drafts/issues/2867,https://github.com/quicwg/base-drafts/issues/2858)

 - [ ] Describe interactions with the transport in terms of defined
      interface terms (https://github.com/quicwg/base-drafts/issues/2857,https://github.com/quicwg/base-drafts/issues/2805)

 - [ ] Require the use of the "http-opportunistic" resource (RFC 8164)
      when scheme is "http" (https://github.com/quicwg/base-drafts/issues/2439,https://github.com/quicwg/base-drafts/issues/2973)

 - [ ] Settings identifiers cannot be duplicated (https://github.com/quicwg/base-drafts/issues/2979)

 - [ ] Changes to SETTINGS frames in 0-RTT (https://github.com/quicwg/base-drafts/issues/2972,https://github.com/quicwg/base-drafts/issues/2790,https://github.com/quicwg/base-drafts/issues/2945):

      *  Servers must send all settings with non-default values in their
         SETTINGS frame, even when resuming

      *  If a client doesn't have settings associated with a 0-RTT
         ticket, it uses the defaults

      *  Servers can't accept early data if they cannot recover the
         settings the client will have remembered

 - [ ] Clarify that Upgrade and the 101 status code are prohibited
      (https://github.com/quicwg/base-drafts/issues/2898,https://github.com/quicwg/base-drafts/issues/2889)

 - [ ] Clarify that frame types reserved for greasing can occur on any
      stream, but frame types reserved due to HTTP/2 correspondence are
      prohibited (https://github.com/quicwg/base-drafts/issues/2997,https://github.com/quicwg/base-drafts/issues/2692,https://github.com/quicwg/base-drafts/issues/2693)

 - [ ] Unknown error codes cannot be treated as errors (https://github.com/quicwg/base-drafts/issues/2998,https://github.com/quicwg/base-drafts/issues/2816)
